version: '3.8'
services:
    
    # Application
    app:
        build:
            context: .
            dockerfile: ./docker/app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "database"

    # Web Server
    web:
        build:
            context: .
            dockerfile: ./docker/web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "app"
        ports:
            - 8080:80

    # Database
    database:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: Temp_DB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: 1234
            MYSQL_USER: db_user
        ports:
            - "33062:3306"


volumes:
    dbdata:
